name: ♻️ Sync GitHub > ForgeEdu

on:
  workflow_dispatch:  # Permet de lancer l'action manuellement
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure Git author
        run: |
          git config --global user.name "laurent.abbal"
          git config --global user.email "laurent.abbal@aefe.fr"

      - name: Sync to ForgeEdu
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://forge.apps.education.fr/cahiers-numeriques/www-cahiernum-net
          target-username: laurent.abbal
          target-token: ${{ secrets.SYNC_GITHUB_TO_FORGEEDU }}
        env:
          GIT_AUTHOR_NAME: "laurent.abbal"  # Nom d'utilisateur GitLab
          GIT_AUTHOR_EMAIL: "laurent.abbal@aefe.fr"  # Email associé à GitLab
          GIT_COMMITTER_NAME: "Laurent Abbal"  # Nom d'utilisateur GitLab
          GIT_COMMITTER_EMAIL: "laurent.abbal@aefe.fr"  # Email associé à GitLab
